### ISSUE TITLE
Error while trying to install using the README instructions.

### ISSUE THREAD

**Issue by barak-haviv** [jcubic/electron-terminal#2]
Working with mac big Sur
node v16
IS there any old node version needed?

> electron-terminal@0.1.0 start
> ./node_modules/.bin/electron .

App threw an error during load
/Volumes/data1/bk/projects/sandbox/electron/nx/app-sandbox/electron-terminal/node_modules/chokidar/index.js:941
  const options = {type: EV_ALL, alwaysStat: true, lstat: true, ...opts};
                                                                ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Volumes/data1/bk/projects/sandbox/electron/nx/app-sandbox/electron-terminal/node_modules/electron-reload/main.js:2:18)

**Comment by jcubic** [comment]
I have no idea, it's an error from `chokidar` not from this project.
Maybe dependencies need to be updated.

**Comment by jcubic** [comment]
I've updated the version of electron, latest doesn't work because of some bug, but updated it to version @12 and it works now.
